technative-academy/Dream-Generator

CSS/global_style.css
CSS selectors finished 
https://trello.com/c/kiMjKVdL/17-global-css-file
=> finish off css selectors

about.html
=> add navbar to about.html

css/footer.css, css/global_style.css, index.html
In global_styles.css file, I moved font-face below imports so imports properly work
In the index.html (soon to be in about.html), there are two footers, one for desktop and one for mobile. This means, one is hidden whilst the other is visible.
the footer.css file has been populated with styles specific for the footer.
=> Footer has been styled with additional information

about.html, css/footer.css, css/home/reviews.css, css/home/statictics.css, index.html
Adding additional classes to the index.html page so element selectors are not used in the footers.css stylesheet.
TBD --> the about page
=> Changing footer element selectors to classes in footers.css

index.html, js/facts.js
Object for facts created  and a dded content using JS.
=> add facts using JS

about.html, css/global_style.css, css/header.css, css/home/hero.css, index.html
Have added styling for the header, nav and hero sections. 
Desktop: 
Mobile:
=> Added header and nav styling

css/about/contact-form.css
Removed a style from the .btn class in the contact-form css page.
=> Added a change to the button styling on home page

about.html, css/about/about-hero.css, css/global_style.css
Added gray background
Changed text of about us
Added new CSS sheet
=> About us hero is fixed

about.html, css/about/company-description.css, css/about/contact-form.css, css/home/facts.css, css/home/sponsors.css, index.html
Sections updates: sponsors, facts, about us desc and contact
=> Fix margin and padding in both pages - different sections

index.html
Have fixed the styling for the mobile nav bar so that it is consistent across all the pages. 
Mobile:
=> Fixing the styling for the nav bar

index.html
Cant share a screenshot but it works!
=> Update path for image hero source

css/header.css
I have added a hover effect/underline animation on the nav bar for desktop and mobile -- when you hover over each nav item a line appears and moves from left to right. 
Desktop: 
Mobile:
=> add hover effect to the nav bar

index.html
Update path in script tags with ./
=> Update paths in script

about.html, index.html
Sign up button is linking to the contact form:
<a href="about.html#sectionID">
=> connect sign-up button

about.html, index.html, products.html
Have added a products page and styling. Also made the nav buttons link to each of the pages, and did the same with all of the footer links.
=> Added a products page and styling

css/home/tabs.css, index.html, js/tabs.js
Removes commented JS in tabs.js file and adds comments
Fixes tabs by hard coding a class into them
Adds hover effects to service buttons
Reduce height of service image
=> Fix tabs by displaying default tab

css/home/facts.css, js/facts.js
Added some more javascript to facts section to create more classes for styling
=> Added styles to facts icons

css/home/sponsors.css
=> Fix sponsors img

css/products/products.css, js/products.js, products.html
Fixed search products. changed class "hide"
Now it filters even there is more products (Show More button clicked).
CSS styles added.
Unfortunately could not resolve number of products.
=> fix filter and add css styles

about.html, css/about/contact-form.css
=> Fix maps responsive view in mobile

about.html, css/about/contact-form.css
Have updated the email address link and also the logo link.
=> Update email and logo link

about.html
Have added a working link to the logo on the about page so that it is consistent across all of the pages.
=> Added link to logo 

index.html
=> fix reviews

css/products/products.css, js/products.js, products.html
=> Fix products styling and making it more similar to design

css/home/sign-up.css, css/home/sponsors.css, index.html, js/products.js
Fixed paragraphs css and removed unnecesarry comments in products.js
=> p fixed / unnecesarry comments removed

css/global_style.css
BRANCH 59 ONWARDS, THINGS GET BROKEN, REVERSING 5/6 COMMITS BEHIND
=> REVERSING MAIN AND REMOVING IMPORT

css/products/products.css, index.html, js/reviews.js
=> FIX SCRIPTS AND JAVASCRIPTS!!!

css/home/statictics.css
fixed styles in css and made text in the center
=> fix css in statisctics

css/home/tabs.css
Have fixed the hover effect on the tabs for desktop and mobile. 
Desktop: 
Mobile:
=> Fixed tabs 
